# Generated by Django 4.2.5 on 2023-12-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("general", "0006_categoria_descripcion"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="cantidad",
            field=models.IntegerField(default=0),
        ),
    ]
