# Generated by Django 4.2.5 on 2023-12-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("general", "0007_producto_cantidad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="nombre",
            field=models.IntegerField(),
        ),
    ]
