# Generated by Django 4.2.5 on 2023-12-09 05:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("general", "0011_alter_comentarios_ranking"),
    ]

    operations = [
        migrations.CreateModel(
            name="carrito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.IntegerField(default=0)),
                ("nombre", models.CharField(max_length=200)),
                ("cantidad", models.IntegerField(default=0)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
